# Generated by Django 3.2.5 on 2021-09-19 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=264, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('alternate_mobil_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line1', models.CharField(max_length=100, unique=True)),
                ('Address_line2', models.CharField(max_length=100, unique=True)),
                ('City', models.CharField(max_length=20, unique=True)),
                ('State', models.CharField(max_length=20, unique=True)),
                ('Zipcode', models.IntegerField(unique=True)),
                ('Country', models.CharField(max_length=246, unique=True)),
                ('publications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma2.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma2.user_id'),
        ),
    ]
