# Generated by Django 3.2.5 on 2021-09-19 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karma2', '0002_auto_20210919_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=264, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('alternate_mobil_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('Address_line1', models.CharField(max_length=100, unique=True)),
                ('Address_line2', models.CharField(max_length=100, unique=True)),
                ('City', models.CharField(max_length=20, unique=True)),
                ('State', models.CharField(max_length=20, unique=True)),
                ('Zipcode', models.IntegerField(unique=True)),
                ('Country', models.CharField(max_length=246, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='user_id',
        ),
    ]
